### ISSUE TITLE
Admin password stored as plaintext

### ISSUE THREAD

**Issue by connor-wool** [CougTech/CustomerLogger#10]
Should use SOME hashing (just hash once using something like MD5 and then compare hashed input to that value).

**Comment by connor-wool** [comment]
![judging_code](https://cloud.githubusercontent.com/assets/15039235/15299424/312bc46e-1b59-11e6-8c74-0c7c32ca4c34.jpg)

**Comment by mweholt** [comment]
Fair enough. we'll work on it

**Comment by JLReitz** [comment]
Fixed this. The admin password is now SHA256-ed and stored within the Windows registry for easy grabbing and comparing.
