### ISSUE TITLE
Add "##CTwi non-cougtech" as 'stealth option' on front page?

### ISSUE THREAD

**Issue by connor-wool** [CougTech/CustomerLogger#19]
Jeff wants a "stealth button" on the front page that allows the greeters to run a ticket for random walk-in issues.

Here's the issues that need to be solved:
- [ ] identify customer on the front page (inherently no ID#, so lets make something up)
- [ ] select the issue on the "issue page" to be this new type (##CTwi - noncougtech)
- [ ] include text into the "describe your issue" field? 
- [ ] submit the form to OTRS

Can we automate this all under a single button on the front page?

**Comment by rodriada000** [comment]
duplicate as quickpicks replace the 'stealth option'
