### ISSUE TITLE
refactor design

### ISSUE THREAD

**Issue by rhuard** [CougTech/CustomerLogger#2]
See comments in the Main window. At the top

This whole program was not the best designed, I sorta hacked it together because I am a back-end dev and needed to get the UI working.

A basic rundown is that the current design is to have one main window and several pages. Each page is meant to get one piece of info from the customer to the system. Each page take a reference to the main window in its constructor that way it can modify the values directly. 

This is not ideal, it probably should be done with some form of events or something. Not just by passing references in with the constructor. At some point re-factoring this would be nice.

See the comments in the main window for more specifics

**Comment by rodriada000** [comment]
all fixed with most recent commit!
