### ISSUE TITLE
Add customer first name to ticket title in OTRS

### ISSUE THREAD

**Issue by connor-wool** [CougTech/CustomerLogger#20]
Current OTRS string looks like this: (EXAMPLE)

##CTapt : Format/Reinstall + Backup : 011354609

We want to modify that string so it looks like this: (EXAMPLE)

##CTapt : Format/Reinstall + Backup : 011354609 : Mohamed

We should be able to grab the users first name from the same place that we get their email (Using the XML parsing from the website that was set up.)

**Comment by rodriada000** [comment]
First name added! waiting on Connor to push new version... closing.
