### ISSUE TITLE
Allow character inputs as code for quick picks

### ISSUE THREAD

**Issue by connor-wool** [CougTech/CustomerLogger#21]
allow people to enter the following codes into "student id" space:

GI - general information
WC - writing center
RF - referral
CT - Coretech

These will push through tickets that have no (or a generic) nid attached, as follows:

CtWi#>>GI

**Comment by connor-wool** [comment]
To do this, we need to add checking into the text box parsing code that looks to see if the user has entered a number or characters. probably something like "Integer.TryParse(text)"

**Comment by rodriada000** [comment]
base code implemented to allow quick picks to be entered into student text box. tickets need to be formatted still as follows: ##CTwi >> GI
