### ISSUE TITLE
Refactor variable names for clarity

### ISSUE THREAD

**Issue by connor-wool** [CougTech/CustomerLogger#23]
Reading through code, there are places where variables have been named poorly and it makes certain sections confusing.

To fix this, we need to rename variables to be more self-documenting.

Most of the work will probably happen in the MainWindow class.

**Comment by JLReitz** [comment]
Completed this. All variables are named as such:

- Prefaced by a "g_" or a "m_" if they are a global or member variable, respectively.
- The prefacing is followed by a lowercase acronym for the type that it is. This then is followed by the name. For instance, a boolean variable could be named "bIsTrue". This is ignored for user-defined types.
